baseURL = "https://vitoriarlima.github.io/"
languageCode = "en-us"
title = "Vitoria Lima"
theme = "ezhil"


# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

copyright = "© Copyright notice"

paginate = 10

# Your Google analytics code.
googleAnalytics = "UA-123-45"
# Your Disqus sortname.
disqusShortname = "localhost"

[params]
    # Blog subtitle which appears below blog title. Supports markdown.

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/myicon.png"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "light" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
    customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
    customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]



# Main menu which appears below site header.
[[menu.main]]
name = "Personal Projects"
url = "/projects"
weight = 5

[[menu.main]]
name = "ML Notes"
url = "/blog"
weight = 3

[[menu.main]]
name = "Books"
url = "/books"
weight = 5


[[menu.main]]
name = "About"
url = "/"
weight = 1


[[menu.main]]
name = "CV"
url = "/cv.pdf"
weight = 2


# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/vitoriarlima"

# Enable tags.
[taxonomies]
   tag = "tags"

# should turn this off whenever we get around to writing shortcodes
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


